#!/usr/bin/env bash
set -e

BUILD_DIR=`readlink -f $0 | xargs dirname`

OE_ENV_SCRIPT="TODO: FIX ME"
export TEMPLATECONF="TODO: FIX ME"
source ${OE_ENV_SCRIPT} ${BUILD_DIR}
unset TEMPLATECONF

bitbake $*
